### ISSUE TITLE
remove frames / values from returned stream data, put into separate route

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-api#5]
to ease heavy traffic it would be better to not include the frames (values) but have them returned through a separate route or additional parameter. for example:

```
GET streams/<uuid>
--> { meta data only }

GET streams/<uuid>/frames
--> { meta data + actual frames }
```

**Comment by dasantonym** [comment]
absolutely, that is what i am currently implementing to solve https://github.com/PieceMeta/piecemeta-angular-frontend/issues/14

there's actually more options to this... i'd like the api client to be able to
- load a full stream
- load only the descriptive data of the stream
- load only the frame data
- load quantized data (every nth frame)
- load a frame range

the last two would require more action on behalf of the api server which is why i'm thinking to move the data storage to hdf5 and throwing out mongodb https://hdfgroup.org/HDF5/
it has native bindings through https://github.com/ryancole/hdf5.node

but for now, those two routes will be quickly implemented.

**Comment by dasantonym** [comment]
http://doc.piecemeta.com/#/get-stream-frames
and 
http://doc.piecemeta.com/#/get-stream-meta

also, the stream index for a channel does not send frame data anymore:
http://doc.piecemeta.com/#/get-streams-for-channel
